# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabbitr < Formula
  desc "rabbitr - CLI tool for RabbitMQ management"
  homepage "https://github.com/smartrecruiters/rabbitr"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.4.0/rabbitr_1.4.0_darwin_arm64.tar.gz"
      sha256 "ea84ff3e222f882d4c0e951af9f852b7d3cba18b49348864ad5bc768b22f3e39"

      def install
        bin.install "rabbitr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.4.0/rabbitr_1.4.0_darwin_amd64.tar.gz"
      sha256 "55f6d0f51d735437298c1b16108f2ed9a8a83ee771584de46d9c2cec1b208de4"

      def install
        bin.install "rabbitr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.4.0/rabbitr_1.4.0_linux_arm64.tar.gz"
      sha256 "bd7bc76dfe3de6febc196a3f98ad5d84629554df27e0a28d219310c72bb6359d"

      def install
        bin.install "rabbitr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.4.0/rabbitr_1.4.0_linux_amd64.tar.gz"
      sha256 "2ee1712f2c7fc337a288bff0ca98d2e610cc8cebaa37863395472fdc7b0b5a49"

      def install
        bin.install "rabbitr"
      end
    end
  end
end
