# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabbitr < Formula
  desc "rabbitr - CLI tool for RabbitMQ management"
  homepage "https://github.com/smartrecruiters/rabbitr"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.5.0/rabbitr_1.5.0_darwin_amd64.tar.gz"
      sha256 "5a06b6c9e7a880d9dc8a9a6862b5655d18f325277aeb24edc76fb3d4dd5f0b8f"

      def install
        bin.install "rabbitr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smartrecruiters/rabbitr/releases/download/1.5.0/rabbitr_1.5.0_darwin_arm64.tar.gz"
      sha256 "fe87f9849dec76d1e6bca8703cea9e6c5ae023535b1299bc927c2895abe7a559"

      def install
        bin.install "rabbitr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/smartrecruiters/rabbitr/releases/download/1.5.0/rabbitr_1.5.0_linux_amd64.tar.gz"
        sha256 "74af7f2376933293a3245d4371525fb7e2ce84f594e61722972dc8bc4d45f5c0"

        def install
          bin.install "rabbitr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/smartrecruiters/rabbitr/releases/download/1.5.0/rabbitr_1.5.0_linux_arm64.tar.gz"
        sha256 "54f918d04c780d2ff30fd2fc10ca92a7a538237124d0b68fdf3d86c51f25f7c7"

        def install
          bin.install "rabbitr"
        end
      end
    end
  end
end
